### ISSUE TITLE
AttributeError: 'WritableTensorData' object has no attribute 'flush_to_disk'

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/pznet#2]
the input patch seems correct now.

```
T_STRIDE_HW=1 ACTIVATION=true ADDOROVERWRITE=false CORES=2 HT=2
dl_filename: /opt/znnphi_interface/lib/conv_true_false_1_2_2_20_36_128_3_1_36_0_0_0_1_1_1_0.so
1 2
1 2
1 2
1 2
1 2

[VolumeDataProvider]
constructing dataset 0...
Forward scan dataset 0
(1/810) loc: (9, 128, 128)
Copying 4718592 bytes into the user input. 
Starting Forward Pass
average:2.21357
Forward Finished
Traceback (most recent call last):
  File "/opt/kaffe/python/forward.py", line 64, in <module>
    fs.push(outs)    # Push current outputs.
  File "/opt/kaffe/DataProvider/python/forward.py", line 64, in push
    self.outputs.push(self.current, sample)
  File "/opt/kaffe/DataProvider/python/blend.py", line 113, in push
    self.data[k].flush_to_disk()
AttributeError: 'WritableTensorData' object has no attribute 'flush_to_disk'
```

**Comment by supersergiy** [comment]
Hi Jingpeng,

Could you give me the docker that you're using? 
I couldn't replicate this error on my c4 instance, so i't a bit hard to tell what's going on.

**Comment by jingpengw** [comment]
the cpu-inference tag
https://hub.docker.com/r/jingpengw/chunkflow.jl/tags/

**Comment by jingpengw** [comment]
I was running locally, do I need to use C4.xlarge in aws?

**Comment by jingpengw** [comment]
usage issue.
